/**
 * Regression corpus for the translation pipeline: end-to-end cases from raw
 * model output to final args, through sanitize -> tokenize -> the real
 * runTranslationPipeline order. Headless, no model needed.
 *
 * The model speaks only template tokens (`-i {input}`, trailing `{output}`)
 * - real paths are resolved at run time. Every user-reported translation
 * failure becomes a case here: set `instruction` (+ `duration`) to the
 * request and `modelRaw` to what the model actually emitted (check the logs
 * - failures now carry it), then pin the correct `expectedArgs`. One case
 * pins aggressive normalization of a non-compliant raw with real paths.
 */
const TRANSLATE_CASES = [
  {
    name: 'last-remove with scale filter',
    instruction: 'Convert to mkv, trim the last 5 seconds, make it 360p',
    duration: 27.49,
    modelRaw: '-i {input} -ss 00:00:00 -t 00:00:05 -vf scale=-2:360 -c:v libx264 -c:a aac {output}',
    expectedArgs: ['-i', '{input}', '-t', '22.49', '-vf', 'scale=-2:360', '-c:v', 'libx264', '-c:a', 'aac', '{output}'],
  },
  {
    name: 'last-keep rewrites -ss/-t',
    instruction: 'keep the last 5 seconds',
    duration: 27.49,
    modelRaw: '-i {input} -ss 00:00:00 -t 00:00:05 {output}',
    expectedArgs: ['-i', '{input}', '-ss', '22.49', '{output}'],
  },
  {
    name: 'last-keep drops truncating -t',
    instruction: 'keep the last 5 seconds',
    duration: 27.49,
    modelRaw: '-i {input} -ss 22.49 -t 2 {output}',
    expectedArgs: ['-i', '{input}', '-ss', '22.49', '{output}'],
  },
  {
    name: 'middle inserts center cut',
    instruction: 'Keep the middle 5 seconds, make it muted',
    duration: 60,
    modelRaw: '-i {input} -an {output}',
    expectedArgs: ['-i', '{input}', '-an', '-ss', '27.5', '-t', '5', '{output}'],
  },
  {
    name: 'middle leaves correct cut alone',
    instruction: 'keep the middle 5 seconds',
    duration: 60,
    modelRaw: '-i {input} -ss 27.5 -t 5 -an {output}',
    expectedArgs: ['-i', '{input}', '-ss', '27.5', '-t', '5', '-an', '{output}'],
  },
  {
    name: 'full request: middle + mute + 720p + greyscale',
    instruction: 'Keep the middle 5 seconds, make it muted, convert to 720p, and make it greyscale',
    duration: 60,
    modelRaw: '-i {input} -ss 27.5 -t 5 -vf scale=-2:720,hue=s=0 -an {output}',
    expectedArgs: ['-i', '{input}', '-ss', '27.5', '-t', '5', '-vf', 'scale=-2:720,hue=s=0', '-an', '{output}'],
  },
  {
    name: 'chit-chat wrapped command',
    instruction: 'Convert to mp4',
    duration: 30,
    modelRaw: 'Hi there! Here is your command:\n-i {input} -c:v libx264 -c:a aac {output}\nLet me know!',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '-c:a', 'aac', '{output}'],
  },
  {
    name: 'fenced answer with binary name',
    instruction: 'convert to mp4',
    duration: 30,
    modelRaw: '```bash\nffmpeg -i {input} -c:v libx264 {output}\n```',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '{output}'],
  },
  {
    name: 'thinking trace stripped',
    instruction: 'convert to mp4',
    duration: 30,
    modelRaw: '<think>let me reason about codecs</think>\n-i {input} -c:v libx264 {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '{output}'],
  },
  {
    name: 'size cap computed and inserted',
    instruction: 'Convert to 1080p mp4 below 100MB',
    duration: 60,
    modelRaw: '-i {input} -vf scale=-2:1080 -c:v libx264 -c:a aac -movflags +faststart {output}',
    expectedArgs: ['-i', '{input}', '-vf', 'scale=-2:1080', '-c:v', 'libx264', '-c:a', 'aac', '-movflags', '+faststart',
      '-b:v', '13573k', '-maxrate', '13573k', '-bufsize', '27146k', '{output}'],
  },
  {
    name: 'size cap bounds copied audio',
    instruction: 'convert below 50MB',
    duration: 60,
    modelRaw: '-i {input} -c:v libx264 -c:a copy {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '-c:a', 'aac', '-b:a', '128k',
      '-b:v', '6722k', '-maxrate', '6722k', '-bufsize', '13444k', '{output}'],
  },
  {
    name: 'two-pass stripped',
    instruction: 'convert to mp4',
    duration: 30,
    modelRaw: '-i {input} -c:v libx264 -pass 1 {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '{output}'],
  },
  {
    name: 'mute strips audio flags',
    instruction: 'convert to webm and mute it',
    duration: 30,
    modelRaw: '-i {input} -c:v libvpx-vp9 -an -c:a libopus {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libvpx-vp9', '-an', '{output}'],
  },
  {
    name: 'copy with filter re-encodes',
    instruction: 'convert to mkv, make it 360p',
    duration: 30,
    modelRaw: '-i {input} -vf scale=-2:360 -c:v copy -c:a aac {output}',
    expectedArgs: ['-i', '{input}', '-vf', 'scale=-2:360', '-c:v', 'libx264', '-c:a', 'aac', '{output}'],
  },
  {
    name: 'duplicate -vf merged',
    instruction: 'make it 720p and greyscale',
    duration: 30,
    modelRaw: '-i {input} -vf scale=-2:720 -vf hue=s=0 {output}',
    expectedArgs: ['-i', '{input}', '-vf', 'scale=-2:720,hue=s=0', '{output}'],
  },
  {
    name: 'bare -s shorthand rewritten',
    instruction: 'make it 360p',
    duration: 30,
    modelRaw: '-i {input} -s 360p {output}',
    expectedArgs: ['-i', '{input}', '-vf', 'scale=-2:360', '{output}'],
  },
  {
    name: 'missing output appended as token',
    instruction: 'convert to webm',
    duration: 30,
    modelRaw: '-i {input} -c:v libvpx-vp9 -c:a libopus',
    expectedArgs: ['-i', '{input}', '-c:v', 'libvpx-vp9', '-c:a', 'libopus', '{output}'],
  },
  {
    name: 'truncated dangling flag dropped',
    instruction: 'convert to mp4',
    duration: 30,
    modelRaw: '-i {input} -c:v libx264 -movflags',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '{output}'],
  },
  {
    name: 'first-keep strips -ss, holds -t',
    instruction: 'keep the first 5 seconds',
    duration: 30,
    modelRaw: '-i {input} -ss 3 -t 9 -c:v libx264 {output}',
    expectedArgs: ['-i', '{input}', '-t', '5', '-c:v', 'libx264', '{output}'],
  },
  {
    name: 'first-remove keeps from N to the end',
    instruction: 'remove the first 5 seconds',
    duration: 30,
    modelRaw: '-i {input} -t 25 {output}',
    expectedArgs: ['-i', '{input}', '-ss', '5', '{output}'],
  },
  {
    name: 'range normalizes window',
    instruction: 'keep seconds 10 to 20',
    duration: 60,
    modelRaw: '-i {input} -ss 0 -t 5 {output}',
    expectedArgs: ['-i', '{input}', '-ss', '10', '-t', '10', '{output}'],
  },
  {
    name: 'honeyed request with thanks',
    instruction: 'Hi there honey! Convert to mp4. Thank you!',
    duration: 30,
    modelRaw: 'Of course honey! Here you go:\n-i {input} -c:v libx264 -c:a aac {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '-c:a', 'aac', '{output}'],
  },
  {
    name: 'speed adds matched audio',
    instruction: 'Speed up 2x',
    duration: 30,
    modelRaw: '-i {input} -vf setpts=0.5*PTS {output}',
    expectedArgs: ['-i', '{input}', '-vf', 'setpts=0.5*PTS', '-af', 'atempo=2', '{output}'],
  },
  {
    name: 'speed with copy re-encodes and syncs',
    instruction: 'Speed up 2x',
    duration: 30,
    modelRaw: '-i {input} -c:v copy {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '-vf', 'setpts=0.5*PTS', '-af', 'atempo=2', '{output}'],
  },
  {
    name: 'fps cap appended',
    instruction: 'Cap it at 30fps',
    duration: 30,
    modelRaw: '-i {input} -c:v libx264 {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '-vf', 'fps=30', '{output}'],
  },
  {
    name: 'width scale appended',
    instruction: 'Make it 640 wide',
    duration: 30,
    modelRaw: '-i {input} -c:v libx264 {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '-vf', 'scale=640:-2', '{output}'],
  },
  {
    name: 'rotation appended',
    instruction: 'Rotate 90 degrees clockwise',
    duration: 30,
    modelRaw: '-i {input} -c:v libx264 {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '-vf', 'transpose=1', '{output}'],
  },
  {
    name: 'volume boosted',
    instruction: 'Boost the volume',
    duration: 30,
    modelRaw: '-i {input} -c:v libx264 -c:a aac {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '-c:a', 'aac', '-af', 'volume=1.5', '{output}'],
  },
  {
    name: 'gif audio stripped to -an',
    instruction: 'Convert to gif',
    duration: 30,
    modelRaw: '-i {input} -vf fps=10,scale=480:-1:flags=lanczos -c:a aac {output}',
    expectedArgs: ['-i', '{input}', '-vf', 'fps=10,scale=480:-1:flags=lanczos', '-an', '{output}'],
  },
  {
    name: 'thumbnail still image',
    instruction: 'Thumbnail at 10 seconds',
    duration: 60,
    modelRaw: '-i {input} -c:v libx264 {output}',
    expectedArgs: ['-i', '{input}', '-ss', '10', '-frames:v', '1', '{output}'],
  },
  {
    name: 'last-keep fixes wrong lone -ss',
    instruction: 'keep the last 5 seconds',
    duration: 27.49,
    modelRaw: '-i {input} -ss 10 {output}',
    expectedArgs: ['-i', '{input}', '-ss', '22.49', '{output}'],
  },
  {
    name: 'gif with libx264 reverts to default encoder',
    instruction: 'Convert to gif',
    duration: 30,
    modelRaw: '-i {input} -c:v libx264 -vf fps=10,scale=480:-1:flags=lanczos -an {output}',
    expectedArgs: ['-i', '{input}', '-vf', 'fps=10,scale=480:-1:flags=lanczos', '-an', '{output}'],
  },
  {
    name: 'thumbnail with libx264 uses image container',
    instruction: 'Thumbnail at 10 seconds',
    duration: 60,
    modelRaw: '-i {input} -c:v libx264 {output}',
    expectedArgs: ['-i', '{input}', '-ss', '10', '-frames:v', '1', '{output}'],
  },
  {
    name: 'slow motion under size limit budgets the longer output',
    instruction: 'slow motion, below 100MB',
    duration: 60,
    modelRaw: '-i {input} -c:v libx264 -vf setpts=2*PTS -af atempo=0.5 -c:a aac {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '-vf', 'setpts=2*PTS', '-af', 'atempo=0.5', '-c:a', 'aac',
      '-b:v', '6722k', '-maxrate', '6722k', '-bufsize', '13444k', '{output}'],
  },
  {
    name: 'remux drops filters, keeps copy',
    instruction: 'Convert mkv to mp4 without re-encoding',
    duration: 30,
    modelRaw: '-i {input} -vf scale=-2:720 -c:v copy -c:a copy {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'copy', '-c:a', 'copy', '{output}'],
  },
  {
    name: 'trim plus thumbnail defers seeking',
    instruction: 'keep the middle 5 seconds, thumbnail at 2 seconds',
    duration: 60,
    modelRaw: '-i {input} -ss 27.5 -t 5 {output}',
    expectedArgs: ['-i', '{input}', '-ss', '27.5', '-t', '5', '-frames:v', '1', '{output}'],
  },
  {
    name: 'explicit speed overrules model setpts',
    instruction: 'Speed up 2x',
    duration: 30,
    modelRaw: '-i {input} -vf setpts=2*PTS -af atempo=0.5 {output}',
    expectedArgs: ['-i', '{input}', '-vf', 'setpts=0.5*PTS', '-af', 'atempo=2', '{output}'],
  },
  {
    name: 'range between form',
    instruction: 'keep between 10 and 20 seconds',
    duration: 60,
    modelRaw: '-i {input} {output}',
    expectedArgs: ['-i', '{input}', '-ss', '10', '-t', '10', '{output}'],
  },
  {
    name: 'duplicate seek collapses before trim',
    instruction: 'keep the last 5 seconds',
    duration: 27.49,
    modelRaw: '-i {input} -ss 10 -ss 22.49 {output}',
    expectedArgs: ['-i', '{input}', '-ss', '22.49', '{output}'],
  },
  {
    name: 'no-op seeks dropped without trim intent',
    instruction: 'convert to mp4',
    duration: 30,
    modelRaw: '-i {input} -ss 0 -t 30 -c:v libx264 {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '{output}'],
  },
  {
    name: 'full-duration -t kept under slow motion',
    instruction: 'slow motion, below 100MB',
    duration: 60,
    modelRaw: '-i {input} -vf setpts=2*PTS -af atempo=0.5 -ss 0 -t 60 -c:v libx264 -c:a aac {output}',
    expectedArgs: ['-i', '{input}', '-vf', 'setpts=2*PTS', '-af', 'atempo=0.5', '-t', '60', '-c:v', 'libx264', '-c:a', 'aac',
      '-b:v', '6722k', '-maxrate', '6722k', '-bufsize', '13444k', '{output}'],
  },
  {
    name: 'real paths are templated',
    instruction: 'Convert to mp4',
    duration: 30,
    modelRaw: '-i C:\\vids\\clip.mp4 -c:v libx264 /tmp/clip-out.mp4',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '{output}'],
  },
  {
    name: 'trim on stream-copy re-encodes',
    instruction: 'keep the last 5 seconds',
    duration: 27.49,
    modelRaw: '-i {input} -c:v copy -c:a aac {output}',
    expectedArgs: ['-i', '{input}', '-c:v', 'libx264', '-c:a', 'aac', '-ss', '22.49', '{output}'],
  },
];

module.exports = { TRANSLATE_CASES };
